### PR TITLE
📝 Readme text changes

### PR DESCRIPTION
**Pull request by Dev-dfm**

### CODE REVIEW

**Review by Maurizio-F — APPROVED** [review]
Nice! 👍🏻

**Review by lajanzen — APPROVED** [review]
🚀

**Review by daebert — APPROVED** [review]
LGTM!

**Review by jujuzitroni — APPROVED** [review]
lgtm

**Review by lajanzen — APPROVED** [review]
🚀

**Review by J-Bannach — APPROVED** [review]
lgtm

**Pull request merged**
